# Generated by Django 4.2.3 on 2023-11-15 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('roll', models.IntegerField()),
                ('city', models.CharField(max_length=150)),
                ('passby', models.CharField(max_length=150)),
            ],
        ),
    ]
